
[ChameleonNowPlaying]
Measure=Plugin
Plugin=Chameleon
Type=File
Path=#@#Images\cover.png
UpdateDivider=100

[ColorForeground1]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Foreground1

[ColorBackground1]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Background1

[ColorForeground2]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Foreground2
OnChangeAction=[!Refresh PlayMusic]

[ColorBackground2]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Background2

[ColorAvg]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Average

[ColorLight1]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Light1

[ColorDark1]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Dark1

[ColorLight2]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Light2

[ColorDark2]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Dark2

[ColorLight3]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Light3

[ColorDark3]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Dark3

[ColorLight4]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Light4

[ColorDark4]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Dark4

[ColorLuminance]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonNowPlaying
Format=Hex
Color=Luminance
