;PlayMusic/@Resources/configStyles.inc

[Variables]
;White
color1=FFFFFF
;Red
color10=E53935
;Orange 
color14=FF5722
;Orange
color3=FF9800
;Yellow
color8=FFD600
;Light Green 
color6=689F38
;Green
color9=43A047
;Teal
color5=00769E
;Cyan
color2=00BCD4
;Blue
color12=1389F4
;Indigo
color11=3F51B5
;Purple
color4=AA22EF
;Deep Purple
color13=673AB7
;Pink
color7=F92E73

[SubHeading]
FontSize=16
FontFace=Segoe UI
FontColor=0,0,0,170
X=83
Y=200
ClipString=2
AntiAlias=1

[BodyText]
FontFace=Segoe UI
FontSize=12
FontColor=30,30,30,240
StringStyle=Normal
StringEffect=Shadow
FontEffectColor = 0,0,0,0
X=3R
ClipString=2
AntiAlias=1

[Checkbox]
X=78
FontSize=11
FontColor=40,40,40,255
SolidColor=0,0,0,0
Padding=5,5,5,5
DynamicVariables=1
AntiAlias=1

[ColorOption]
H=38
W=38
X=1R
Y=r