;PlayMusic/@Resources/Styles.inc

[Variables]
MeterTitleName=MeterTitle
MeterArtistName=MeterArtist
MeterAlbumName=MeterAlbum
MeterCurrentTime=MeterTime
StatusImg=#@#images\play.png
AppPath="C:%HOMEPATH%\AppData\Local\GPMDP_3\Update.exe --processStart Google%20Play%20Music%20Desktop%20Player.exe"
ReadPath="C:%HOMEPATH%\AppData\Roaming\Google Play Music Desktop Player\json_store\playback.json"

[TextStyle]
FontFace=Monospaced
FontSize=12
FontColor=255,255,255,250
StringEffect=Shadow
FontEffectColor=0,0,0,225
X=95
H=20
W=153
ClipString=1
AntiAlias=1
DynamicVariables=1

[Status]
ImageTint=245,245,245
X=250
H=20
W=20
