[Variables]

;This determines the PlayMusic variant used by the skin (Default: Landscape)
variant=Round

;This determines the accent color used by the skin (Default: FFFFFF89)
;This is the variable that determines the accent color used by the skin
accent=FF9800F1

;This is the icon variant used when the skin is minimized
icon=C:\Users\there\Documents\Rainmeter\Skins\PlayMusic\@Resources\images\icon_fill.png

;This is the variable used to scale each of the skins (Default: 5)
size=4.5

;This determines whether the skin minimizes when GPMDP is closed (0 = off, on = 1) 
minimizeOnClose=1

;This variable determines whether the visualizer is shown 
showVisualizer=1

;This determines the color of the visualizer bars
barColor=255,255,255,90

;Tells the skin whether 'Playback API' is enabled in GPMDP
playbackAPI=1

;These variables determines which theme and text color is used by the skin
theme=Dark
textColor=25,25,25,225

;Tells the skin whether volume control is enabled
enableVolumeControl=1

;This variable determines the increments that the volume increases/decreases
volumeStep=2

;This variable determines the width of the bands in the visualizer
wideBands=0
