;PlayMusic/@Resources/Include/RoundBands,inc

[MeterBand1]
Meter=Bar
MeasureName=MeasureBand1
MeterStyle=VisualizerStyle
; Y=(#size#*12)+((4.5-#size#)*10)
Y=((#RoundHeight#/3.8))
H=(#size#*21.4)
[MeterBand2]
Meter=Bar
MeasureName=MeasureBand2
MeterStyle=VisualizerStyle
; Y=(#size#*9.5)+((4.5-#size#)*10)
Y=(#size#*9.5)
[MeterBand3]
Meter=Bar
MeasureName=MeasureBand3
MeterStyle=VisualizerStyle
; Y=(#size#*11.9)+((4.5-#size#)*10)
Y=(#size#*11.4)
[MeterBand4]
Meter=Bar
MeasureName=MeasureBand4
MeterStyle=VisualizerStyle
; Y=(#size#*13.5)+((4.5-#size#)*10)
Y=(#size#*12.8)
[MeterBand5]
Meter=Bar
MeasureName=MeasureBand5
MeterStyle=VisualizerStyle
; Y=(#size#*14.6)+((4.5-#size#)*10)
Y=(#size#*13.9)
[MeterBand6]
Meter=Bar
MeasureName=MeasureBand6
MeterStyle=VisualizerStyle
; Y=(#size#*15.5)+((4.5-#size#)*10)
Y=(#size#*15)
[MeterBand7]
Meter=Bar
MeasureName=MeasureBand7
MeterStyle=VisualizerStyle
; Y=(#size#*16.4)+((4.5-#size#)*10)
Y=(#size#*15.8)
[MeterBand8]
Meter=Bar
MeasureName=MeasureBand8
MeterStyle=VisualizerStyle
; Y=(#size#*17.1)+((4.5-#size#)*10)
Y=(#size#*16.6)
[MeterBand9]
Meter=Bar
MeasureName=MeasureBand9
MeterStyle=VisualizerStyle
; Y=(#size#*17.7)+((4.5-#size#)*10)
Y=(#size#*17.1)
[MeterBand10]
Meter=Bar
MeasureName=MeasureBand10
MeterStyle=VisualizerStyle
; Y=(#size#*18.2)+((4.5-#size#)*10)
Y=(#size#*17.2)
[MeterBand11]
Meter=Bar
MeasureName=MeasureBand11
MeterStyle=VisualizerStyle
; Y=(#size#*18.3)+((4.5-#size#)*10)
Y=(#size#*17.5)
[MeterBand12]
Meter=Bar
MeasureName=MeasureBand12
MeterStyle=VisualizerStyle
; Y=(#size#*18.4)+((4.5-#size#)*10)
Y=(#size#*17.6)
[MeterBand13]
Meter=Bar
MeasureName=MeasureBand13
MeterStyle=VisualizerStyle
; Y=(#size#*18.4)+((4.5-#size#)*10)
Y=(#size#*17.6)
[MeterBand14]
Meter=Bar
MeasureName=MeasureBand14
MeterStyle=VisualizerStyle
; Y=(#size#*18.4)+((4.5-#size#)*10)
Y=(#size#*17.6)
[MeterBand15]
Meter=Bar
MeasureName=MeasureBand15
MeterStyle=VisualizerStyle
; Y=(#size#*18.3)+((4.5-#size#)*10)
Y=(#size#*17.5)
[MeterBand16]
Meter=Bar
MeasureName=MeasureBand16
MeterStyle=VisualizerStyle
; Y=(#size#*17.8)+((4.5-#size#)*10)
Y=(#size#*17.1)
[MeterBand17]
Meter=Bar
MeasureName=MeasureBand17
MeterStyle=VisualizerStyle
; Y=(#size#*17.5)+((4.5-#size#)*10)
Y=(#size#*17)
[MeterBand18]
Meter=Bar
MeasureName=MeasureBand18
MeterStyle=VisualizerStyle
; Y=(#size#*17)+((4.5-#size#)*10)
Y=(#size#*16.4)
[MeterBand19]
Meter=Bar
MeasureName=MeasureBand19
MeterStyle=VisualizerStyle
; Y=(#size#*16.2)+((4.5-#size#)*10)
Y=(#size#*15.7)
[MeterBand20]
Meter=Bar
MeasureName=MeasureBand20
MeterStyle=VisualizerStyle
; Y=(#size#*15.3)+((4.5-#size#)*10)
Y=(#size#*14.9)
[MeterBand21]
Meter=Bar
MeasureName=MeasureBand21
MeterStyle=VisualizerStyle
; Y=(#size#*14.3)+((4.5-#size#)*10)
Y=(#size#*14.1)
[MeterBand22]
Meter=Bar
MeasureName=MeasureBand22
MeterStyle=VisualizerStyle
; Y=(#size#*13.2)+((4.5-#size#)*10)
Y=(#size#*12.7)
[MeterBand23]
Meter=Bar
MeasureName=MeasureBand23
MeterStyle=VisualizerStyle
; Y=(#size#*11.6)+((4.5-#size#)*10)
Y=(#size#*11.3)
[MeterBand24]
Meter=Bar
MeasureName=MeasureBand24
MeterStyle=VisualizerStyle
; Y=(#size#*9.8)+((4.5-#size#)*10)
Y=(#size#*9.2)
[MeterBand25]
Meter=Bar
MeasureName=MeasureBand25
MeterStyle=VisualizerStyle
; Y=(#size#*12)+((4.5-#size#)*10)
; Y=7(#size#*(12*(#size#-4.5))
Y=((#RoundHeight#/3.8))
H=(#size#*21.4)
